### ISSUE TITLE
Remaining mockups needed

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#1]
- ~~Icon for child under 5 years in add member pop-up~~ Moved to https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/10
- ~~Icon for other family member in add member pop-up~~ Moved to https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/10
- ~~Icon for add family page~~ Removed
- [x] Pop-up for remove member button - selecting which member, or entire family, to remove 
- [x] Transfer family head and primary caregiver status to another member
- [ ] ~~Separate out death reporting from other remove reasons~~
- [ ] TBD: Pop up for primary caregiver in U5 child registration form
- [x] Family survey button - due monthly
- [x] Edit family member button - opens their previous registration form
- [ ] Family member profile page when there are no services for that family member
- [x] Family "Activity" tab - shows timeline of most recent visits
- ~~Observations & Illness Episodes always optional, never required, separate from home visit~~ RW: removed, discussion below
- [ ] Birth certificate workflow during home visit (series of 4-5 questions)
- [ ] Fully immunized status - 1 yr and 2 yrs - in the history, and perhaps after they finished last vaccine, get a pop up
- [ ] Notification for child record being removed from child list?
- [x] Show deceased members in family record
- [ ] Register ANC button for all women of reproductive age
- [x] Where to show family registration details, like source of income

**Comment by rowo** [comment]
@cagulas I moved the question content assets to https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/3.

**Comment by rowo** [comment]
@cagulas please take a look at the wireframe sketches on https://marvelapp.com/project/3394173/. I added the above with placeholders for form content since those should be handled consistently and is still being discussed separately.

For making another person head of family, would that be part of an individual's registration or would that need to be an option from the family profile? I'm thinking the latter.

**Comment by cagulas** [comment]
Things are looking good for the mockups!

**Comment by rowo** [comment]
Need to add registers: All Families, ANC, Child

**Comment by cagulas** [comment]
To discuss with @rowo and @keymane, final round of mockups in Marvel:

- [ ] Filter/sort menu missing currently. Are these needed? If they are only default-sorted by last updated, and the user can't change the sort, then the families with due home visits could get buried down at the bottom. So having a sort by most due to least due could be very useful. Also, having a location filter could be really useful as well, if they're traveling to a particular location for work that day. Proposed list of sort and filter parameters are listed in the project brief.

- [ ] For discussion: Do we need to separate the family registration from the head of family registration? Currently, they are in the same "Add Family" form; first the user records the family location details, then the head of family details. The issue is, if you want to go back and edit either the family details or edit the family head details, it comes from the same form, but the edit buttons for each are in different places in the app. Similarly, if you transfer family head status to another family member, then the original family registration form doesn't apply to the same person anymore. I see either of two solutions: 1) We leave the family registration form as is (i.e. both family and family head are registered in the same form), but for editing purposes, we split the form, so the user opens separate forms to edit the family details or the family head details, respectively; or 2) We remove the family head registration from the "Add family" form, so that the form only registers the family entity. The family head is then registered as just another family member. We might have to automatically default the first family member registered as the family head and primary caregiver then. @keymane can you weigh in on this from a technical perspective, i.e the implications of doing one or the other?

- [ ] For discussion: When registering a child, a primary caregiver needs to be specified. We are requiring the primary caregiver to be a member of the family. It makes sense to be able to show the primary caregiver of the family when registering a child to confirm that's the correct primary caregiver. If not the correct primary caregiver, then the user should have the option to choose another, but only from the list of family members, because I don't think we want to support a family member registration within the U5 child registration form. I think this scenario also supports option 1 in the point above about keeping family and family head in the same registration form, so that you avoid a scenario where a child is being registered without another member in the household already registered. @rowo and @keymane do you both agree with this approach? If so, Roger, we will need quick mockup for this.

- [ ] For @keymane: I assume each family entity needs a unique ID in the database, but do we need a human-friendly ID for the family shown in the register for the health worker? Each member will have an ID displayed, but does the family entity itself also need an ID displayed? I don't think the health workers typically assign any IDs to households, so not sure this is necessary from a user point of view.

- [ ] @rowo We still need to account for the obs & illness episodes. From our last discussion, we talked about having it always available, but optional, and separate from the home visit form.

**Comment by rowo** [comment]
@cagulas 
- Re: filters: I added a filter button (in Marvel), but I think the labels need some work so they can both fit in the space and be clear. The word "last" is not clear, I think maybe it's being misused in the Marvel comment.
- Re: Splitting form for family details and family head: seems more like a technical issue or maybe I don't understand it. I'm not sure why they couldn't just be on two steps/pages (like they are designed anyways because of the length), and each page is submitted as separate forms and a family is only officially created in the system if the family head gets registered.
- Re: Caregiver: This is similar to the previous bullet. If you can technically just have two separate "pages" come right after another and be separate forms, you can just make it seem like a single workflow. So for this, you could register a child and if you are saying we have to verify the primary caregiver every time, just go straight to the edit primary caregiver form right after a child registration i.e. something like https://marvelapp.com/project/3394173/screen/50051302 but we can edit or remove the title. Is there only one primary caregiver per family or is it per child?
- Re: obs and illness, if we zoom out and look at it from a platform level — is the goal that this is medical data that can be entered at anytime versus more other inputs that are only available after a certain interval has passed? It seems like with the new approach where anything can be entered anytime, just including all data entry in the visit form would be simpler to learn. It could just be called a "visit form" so it's just remembered as the form you click on anytime you visit. 
- Re: upcoming. I was thinking about this and ran into a quirk. I was about to add it as a "to do" on the monthly visit form. However, the upcoming to-do's are partially based on what you didn't do in that current visit — so for a full list we'd have to show it after the form has been submitted. That kind of took me back to the profile. So there, we can really only show what's due in the upcoming visit, meaning this is basically just a list of services connected to the next home visit, even if the next home visit is today. So basically, I think just showing on the profile is fine, but it will be connected to the "child home visit" button and so will appear slightly different whether that button is active or not. Visual to be done, but please let me know what you think.
- "Last visit time" seems a little bit like too much detail to me since basically the only thing that matters isn't the exact time — it's just that if that time is over 1 month. Given this, what do you think about just highlighting in red buttons the people that havne't been visited in 2 or more months as seen in https://marvelapp.com/project/3394173/screen/48411528? I also had a questions on Slack — if we take cues from the Reveal app, they have a similar workflow where they need to see everybody in one campaign. But they have a button that's basically "visited but didn't do service". I was thinking this would help CHWs keep track of work if they know they won't be going back to that area again. I like this solution better than a "mute" bc the consequences are still clear (family will show up red next month).

**Comment by cagulas** [comment]
@rowo For the family head/primary caregiver related questions, see the previous thread, which I edited in bold. I did speak to Eph on this one, so the feedback for you is listed there.

**Comment by rowo** [comment]
@cagulas @keymane Ok, there just isn't really an explanation — the reasoning is it just that it's easy to do editing as new forms. So I was just wondering — is it especially difficult to do two separate forms i.e. do family details then go straight into a family head registration?

Since, as far as confirming primary caregiver, I like just pointing them to that existing caregiver form after the U5 registration and the caregiver is bulleted. But we can also just create a new identical form too..just wondering what the plan is.

**Comment by cagulas** [comment]
@rowo Replied to your latest comments. This issue has gotten too long, so I'm closing, and anything unfinished I'll create separate issues for. I think everything is complete though. Eph has created a separate assets list for you.
