### ISSUE TITLE
Improve the workflow for recording vaccine history

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#142]
Right now, if you register an older child, let's say a 4 year old, when you open their first home visit form, it shows only the birth immunizations overdue row. It becomes confusing because after you record the birth vaccines, the birth immunization row in the home visit screen disappears and it's replaced by immunizations 6w, and so on until you finish recording all vaccines, and then you see a screen where it shows all vaccines recorded in the same row, see below:

![screenshot_20190219-145553](https://user-images.githubusercontent.com/3488986/53013406-cc3ea480-3456-11e9-9ebb-58f0a5d4934e.png)

I'll consult with @rowo on this tomorrow, but I think it might be better to keep all immunization rows separate. One idea might be to show all immunization rows when you first open the home visit, but the later immunizations are disabled (and greyed out) until all earlier immunizations are marked as done. Another option may be to only show birth immunizations, but after they're recorded, the birth immunization row still shows, but then add the next immunization row right after it.

@keymane Would like to hear your thoughts on feasibility of these options.

**Comment by raihan-mpower** [comment]
@cagulas this would need a verdict soon , as the changes suggested might need good amount of work.

**Comment by cagulas** [comment]
@raihan-mpower noted. I hope to do this tomorrow. Please weigh in as well with your thoughts on what's feasible from your end.

**Comment by rowo** [comment]
@raihan-mpower: Carolyn and I discussed showing the due vaccines up to the date of the registered child as disabled items in the list.

Current vs. what we're thinking:
<img width="746" alt="screen shot 2019-02-20 at 10 34 50 pm" src="https://user-images.githubusercontent.com/1584163/53141881-d8625900-355f-11e9-9360-fdbce82cfcee.png">

- Since the person on the right was registered at 16 weeks, the immunizations from birth up to 14 weeks are shown. 
- The disabled state is represented by a list circle (#EEEEEE), lighter text (#AAAAAA) and some message on why the item is disabled (right now = "Fill earlier immunization" in italic). @cagulas can you provide input on what that second line should say?
- I'm not sure if this rule applies to the other items like breastfeeding, Vit A, etc. @cagulas ?
- Also related is #143, which looks expiring list items and not showing them at all if children are registered beyond certain age thresholds. @cagulas will update that issue soon I'm guessing.

**Comment by cagulas** [comment]
@rowo I don't think it needs to apply to any other service apart from vaccines. The reasoning is that other services don't rely on strict sequencing. E.g. A child should receive vitamin A every 6 months, but although we track how many doses they receive in total (for coverage and performance assessment), they're all the same dose and if they miss a dose or get an extra dose somehow, it doesn't impact when the next one should be given. There's no such thing as fully Vitamin A'ed or fully dewormed, like there is for fully immunized.

For the wording of the greyed out text, I think "Record earlier immunizations" is ok.

@raihan-mpower @keymane What do you both think?

**Comment by mahmud6390** [comment]
[device-2019-02-27-195438.mp4.tar.gz](https://github.com/OpenSRP/opensrp-unicef-wcaro/files/2910657/device-2019-02-27-195438.mp4.tar.gz)
@cagulas  added the output video

**Comment by cagulas** [comment]
- Can you change "Fill earlier immunization" text to "Record earlier immunizations"
- Make "Record earlier immunizations" italic font
- Add a space in "atbirth" on the home visit screen after birth immunizations are recorded.

Otherwise, looks great!!!

**Comment by cagulas** [comment]
Lgtm
