### ISSUE TITLE
Child monthly home visit schedule should be based on calendar month

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#151]
Feb 15th build:

- [x] Let's confirm we are scheduling this by calendar months, not by number of days. E.g. I registered a family and kid today, and the home visit is due. If I don't complete the home visit, it should become overdue on March 1st. Right now, it doesn't become overdue until April 1st.

**Comment by rkodev** [comment]
All children without an initial home visit are stuck in due status the second month after registration. 
The suggestion is to use the date of registration to check if the child's visit status is overdue for the initial visit. 
This happens because the child has no last visit date to calculate the overdue status for the 1st month in such cases

**Comment by cagulas** [comment]
Lgtm
