### ISSUE TITLE
Assets from UNICEF

### ISSUE THREAD

**Issue by rowo** [OpenSRP/opensrp-unicef-wcaro#3]
- [ ] Assets for each type of child health service (CG to check first if UNICEF has anything we can use):
- Immunization - oral and injection
- Exclusive Breastfeeding
- MNP packs
- Vitamin A
- Deworming
- Dietary Diversification
- MUAC
- Diarrhea and ORS/Zinc provided
- Sleeping under LLITN
- Development milestones
- Stimulation skills of caretaker
- Early learning program

**Comment by rowo** [comment]
@cagulas assigning this to you for now — please post client assets here and reassign when we get everything.

**Comment by cagulas** [comment]
Assets sent over email.

**Comment by cagulas** [comment]
Closing this. Please reach out to Roger for the specific assets you need as you start work on each issue.

**Comment by rowo** [comment]
@cagulas I didn't see good representations for the the icons below. Could you check to see if if I missed something?

- Deworming
- MUAC
- Diarrhea and ORS/Zinc provided
- Development milestones
- Stimulation skills of caretaker
- Early learning program

**Comment by cagulas** [comment]
There's #2, for nutrition. I guess that could kind of work. 66 for deworming could work. There is a 167 for ORS, but Liberia is not doing it. Let me ask Hawi. We just need deworming for now, since Liberia is not doing the rest.

**Comment by rowo** [comment]
@cagulas Were you saying the nutrition icon for MUAC? 

Also 66 is the supplies box right? 
<img width="121" alt="screen shot 2018-12-12 at 2 47 24 am" src="https://user-images.githubusercontent.com/1584163/49854538-74c9eb80-fdb8-11e8-9ead-d2cbc88c9e20.png">

167 for ORS looks good. I think in the issue it was listed as "Diarrhea and ORS/Zinc provided". Is it still that combination question?

**Comment by cagulas** [comment]
@rowo On second thought, that nutrition one probably wouldn't be good for MUAC, since it's about that tape to measure MUAC. The deworming one is that pill. I must have gotten the number wrong. It's a pill or tablet that they give for deworming. The rest we don't need for now, because Liberia is not doing them.

**Comment by cagulas** [comment]
@rowo right now, we don't need them. We may or may not need them for the next country. We don't know yet. I also can't give you a timeline for when the next country's requirements will be ready for us to know then. Right now, we only need deworming. That's the only thing I can say definitively right now. Despite this, I have emailed Hawi and asked for the others, so that we have them anyway.

**Comment by rowo** [comment]
@cagulas Ok, I understand we don't need them right now that is clear to me. I was just hoping the requirements were more set so I wouldn't have to context-switch back to this later since that takes time. But sounds like they may or may not be a requirement, so I will just consider them as "not required" until they are.

**Comment by rowo** [comment]
@cagulas I put modifications into the xxhdpi folder in Drive. See screenshot of folderbelow. The little cloud thing is a sync icon and I'm using dark theme on OSX. I actually used some [UNOCHA's new icon set](https://thenounproject.com/ochavisual/collection/ocha-humanitarian-icons-v02/) for some stuff.

<img width="505" alt="screen shot 2018-12-17 at 10 57 48 pm" src="https://user-images.githubusercontent.com/1584163/50131317-9bbc6d80-024f-11e9-88db-abfda2d3a419.png">
