### ISSUE TITLE
Primary caregiver needs phone number discussion

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#5]
@rowo I was just thinking that a primary caregiver needs a phone number, and currently, if the family member is not a primary caregiver, a phone number is not required in their registration form. So, if they are changed to a primary caregiver later on, we need a way to record their phone number and make it mandatory. We might need to support a separate new workflow that opens their registration form again to now record a phone number and make it mandatory, or a separate full-screen dialog to record phone number after selecting them as primary caregiver. I guess same thing goes for the family head.

**Comment by rowo** [comment]
Ok. If someone is selected to be a primary caregiver, and we are requiring all caregivers have numbers, then it seems to make sense to fill in a number if the chosen caregiver doesn't have a number. It would be nice to just be prompted to enter that person's number in the same select caregiver form so that it completes a single interaction. Otherwise, if you have to go to another form, it's not as clear that a new caregiver was "saved" or not. This implies that when the Change Caregiver [or Head] form is opened, OpenSRP would know the statuses and next steps for each option.

The broader pattern you are talking about is role-based fields that need to be filled out. If the forms are set up in a way so role-based questions are separated out from member-based questions, we could treat this like the family details vs. family head situation. It is pretty similar in that you would not want to go to the full registration, you would only want to fill in what you need to do.

**Comment by cagulas** [comment]
@rowo Left some comments for you above inline.

**Comment by rowo** [comment]
@cagulas I added a workflow on Marvel (https://marvelapp.com/9j1277a/screen/50051302) that takes you to either a phone number entry or a confirm phone number. Doing it within this form means you cannot define a new caregiver or head without the required phone number information.

**Comment by cagulas** [comment]
@rowo This makes sense. Thanks for providing the mockup. I'm ok going with this approach. I forgot to mention in the first comment, but it's not just phone number, it's phone number, other phone number, and education level, but I think it still works with this approach.
